#!/bin/bash
# Install Unzip
sudo apt-get install unzip
#Download latest version of the terraform
wget https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
#Extract the downloaded file archive
unzip terraform_0.11.8_linux_amd64.zip
#Move the executable into a directory searched for executables
sudo mv terraform /usr/local/bin/
#Run it
terraform --version 
